### ISSUE TITLE
pyprofibus hardware documentation

### ISSUE THREAD

**Issue by omidfathi** [mbuesch/pyprofibus#22] opened 2022-01-15 13:08 UTC
hello

pyprofibus hardware documentation which is linked, doesn't work.

thanks for your work

**Comment by mbuesch** [comment] 2022-01-16 18:36
Thanks for your message.
The documentation links work correctly in the pyprofibus release packages only.

**Comment by mbuesch** [comment] 2022-01-16 18:38
Duplicate of #6

**Comment by mbuesch** [comment] 2022-01-16 20:19
The master branch commit baea2df6e3ead2f5f1fa16d15867c4649cf50d1a changes pyprofibus documentation links to work correctly in checkout and release archive.
Can you please check if this works for you?
Thanks!

**Closed** 2022-01-20 18:29 UTC
Labels: duplicate
